### ISSUE TITLE
Wrong Chrome Rendering

### ISSUE THREAD

**Issue by Cophla** [aliftype/amiri#208]
![Untitled](https://user-images.githubusercontent.com/16767283/106011542-3d674780-60c3-11eb-9cb8-283cd62d7c18.png)

Dear Developers, 
thank you for the great font
i'm facing a chrome rendering issues with the font like seen in the image above 
on firefox its working normally
see:
محمد
الله
have wrong rendering, if i change the web page zoom the font re-renders accurately
i'm using latest version 0.113 ttf files

CSS for the Font:
```CSS
@font-face {
    font-family: 'AmiriWeb';
    src: url('Amiri-Regular.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
    font-display: swap;
}

@font-face {
    font-family: 'AmiriWeb';
    src: url('Amiri-Bold.ttf') format('truetype');
    font-weight: bold;
    font-style: normal;
    font-display: swap;
}

@font-face {
    font-family: 'AmiriWeb';
    src: url('Amiri-Slanted.ttf') format('truetype');
    font-weight: normal;
    font-style: italic;
    font-display: swap;
}

@font-face {
    font-family: 'AmiriWeb';
    src: url('Amiri-BoldSlanted.ttf') format('truetype');
    font-weight: bold;
    font-style: italic;
    font-display: swap;
}
```
